services:
  mongo:
    image: mongo:7
    container_name: raidnotificator-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  bot:
    build:
      context: .
      dockerfile: RaidNotificator/Dockerfile
    container_name: raidnotificator-bot
    restart: unless-stopped
    depends_on:
      - mongo
    user: "0:0"
    environment:
      DCToken: ${DCToken}
      GuildId: ${GuildId}
      ChannelName: ${ChannelName}
      ConnectionStrings__MongoDBConnectionStringDev: mongodb://localhost:27017
      ConnectionStrings__MongoDBConnectionStringProd: mongodb://mongo:27017

volumes:
  mongo_data: